spring:
  application:
    name: halo_shop
  datasource:
    url: jdbc:mysql://localhost:3306/haloshop
    username: root
    password: 2511
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8994
